### ISSUE TITLE
employees.txt is missing from www/ folder

### ISSUE THREAD

**Issue by dsteplight** [deminy/behat-rest-testing#3]
Where is the sample employees file? It seems to be missing.

**Comment by deminy** [comment]
There is no need to have that file in place (as part of the Git repository), since it serves only as a backend storage system. To understand data stored in that text file, please kindly check comments in file [www/router.php](https://github.com/deminy/behat-rest-testing/blob/master/www/router.php). I'd already had them described over there. Thanks

**Comment by deminy** [comment]
I've changed data format from PHP serialized string to JSON, and added a sample file [sample.employees.json](https://github.com/deminy/behat-rest-testing/blob/master/www/sample.employees.json) to show data structure of test data.

Hope it helps. Closing issue now.
